---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  network:
  - ["forwarded_port", {guest: 8080, host: 8080}]

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.4
    run_list:
      - recipe[yum::default]
  # - name: ubuntu-12.04
  #   run_list:
  #     - recipe[apt::default]

suites:
  - name: default
    run_list:
      - recipe[tcserver::default]
    attributes: