AllCops:
  Includes:
    - Berksfile
    - Gemfile
    - Rakefile
  Excludes:
    - vendor/**
    - metadata.rb

AlignParameters:
  Enabled: false
Encoding:
  Enabled: false
HashSyntax:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Max: 30
